# Generated by Django 5.0 on 2023-12-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=120)),
                ('familya', models.CharField(max_length=120)),
                ('manzil', models.CharField(max_length=150)),
                ('mamlakat', models.CharField(max_length=150)),
                ('yoshi', models.IntegerField()),
            ],
        ),
    ]
